### ISSUE TITLE
enable zenodo integration to make script citable

### ISSUE THREAD

**Issue by jhpoelen** [ParasiteTracker/tpt-reporting#10]
A copy of a generated tpt report is now available via Poelen, Jorrit H., & Seltmann, Katja C. (2020). Terrestrial Parasite Tracker indexed biotic interactions and review summary (Version 0.1) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3685365 . 

To help cite the specific version of the generation script used to generate the report, we can [enable a Zenodo integration](https://guides.github.com/activities/citable-code/). For some reason, my Zenodo account does not let me enable the https://github.com/ParasiteTracker/tpt-reporting in the Zenodo github page, even after becoming an owner of the tpt-reporting org. 

@seltmann since you first created the parasitetracker github org, can you check whether you can "flip-the-switch" to enable the Zenodo-github integration?

**Comment by seltmann** [comment]
@jhpoelen switch has been flipped

**Comment by jhpoelen** [comment]
@seltmann thanks!

I've added references by doi to TPT data paper http://doi.org/10.5281/zenodo.3685365 (see screenshot) . 

![Screenshot from 2020-02-27 11-11-46](https://user-images.githubusercontent.com/1084872/75478095-36373700-5952-11ea-89c3-3ffa4ae81487.png)

Would it be an idea to cite all GBIF dataset DOIs of TPT affiated collections this way? Perhaps this would count for the GBIF citation statistics software.

**Comment by jhpoelen** [comment]
related to #9

**Comment by jhpoelen** [comment]
@seltmann thanks for enabling Zenodo integration. I've created a Zenodo publication by making a github release - 

Jorrit Poelen. (2020, February 27). ParasiteTracker/tpt-reporting: TPT Workshop 2020-02-24 release (Version 0.0.1). Zenodo. http://doi.org/10.5281/zenodo.3690022

Unfortunately, I am unable to edit the meta data for the Zenodo pub to add your name as an author ; ( .
