### ISSUE TITLE
April 28 TPT report

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#16]
@jhpoelen @zaspelj I reran the report on all of the TPT datasets presently indexed by GloBI for a new quarterly data publication (last publication https://zenodo.org/record/3685365#.XqN_tVNKjOQ).

I would like some suggestions around organization of the tpt-reporting repo to enable frequent publications.

Thanks for your suggestions,
Katja

globalbioticinteractions/ucsb-izc
globalbioticinteractions/fmnh
globalbioticinteractions/mpm
globalbioticinteractions/ummzi
globalbioticinteractions/inhs-insects
globalbioticinteractions/vectorbase
globalbioticinteractions/vertnet
globalbioticinteractions/scan

**Comment by jhpoelen** [comment]
@seltmann  thanks for helping to prepare the report. 

From the parasite tracker integration table -
```
$ curl -Ls "https://raw.githubusercontent.com/globalbioticinteractions/globalbioticinteractions.github.io/master/_data/parasitetracker.tsv" | tail -n+2 | cut -f9 | sort | uniq

globalbioticinteractions/fmnh
globalbioticinteractions/inhs-insects
globalbioticinteractions/mpm
globalbioticinteractions/scan
globalbioticinteractions/tamuic-ent
globalbioticinteractions/ucsb-izc
globalbioticinteractions/ummzi
globalbioticinteractions/unhc
globalbioticinteractions/usnmentflea
globalbioticinteractions/vectorbase
globalbioticinteractions/vertnet
```

so, looks like 

globalbioticinteractions/usnmentflea
globalbioticinteractions/unhc
globalbioticinteractions/tamuic-ent
globalbioticinteractions/usnmentflea

need to be added to the datasets.tsv .

**Comment by jhpoelen** [comment]
What kind of feedback on the repo are you looking for? Automation scripts?

**Comment by seltmann** [comment]
This is the kind of feedback I was looking for. I am creating some documentation on how to generate a report in the README.

**Comment by seltmann** [comment]
@jhpoelen  
I see that tpt-reporting and elton software releases are linked to the report. 
10.5281/zenodo.3690022 (Software), 10.5281/zenodo.3679356 (Software)

elton 0.95 release is here: https://zenodo.org/record/3748065#.Xqih5VNKjOQ and we need a new release of tpt-reporting? New release each time makes sense to me.

**Comment by jhpoelen** [comment]
Sounds like a good plan to me!

**Comment by seltmann** [comment]
@jhpoelen created the software tpt-reporting (v.0.0.2) for release (https://zenodo.org/deposit/3776419). Not sure if you can see to review?

**Comment by jhpoelen** [comment]
Cool! Unfortunately, I cannot see the deposit (see attached screenshot). Review by whereby instead?

![Screenshot from 2020-04-29 11-57-11](https://user-images.githubusercontent.com/1084872/80635419-b6405280-8a10-11ea-94e3-47f6d5e05dc4.png)

**Comment by seltmann** [comment]
That would be great. https://whereby.com/cheadle-center

**Comment by jhpoelen** [comment]
The TPT report was since published at 

>Poelen, Jorrit H., Seltmann, Katja C., & Campbell, Mariel. (2020). Terrestrial Parasite Tracker indexed biotic interactions and review summary (Version 0.2) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3778773
