### ISSUE TITLE
Publish review README errors

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#18]
@jhpoelen the present report README is dropping characters in the text:

notice 

> Datasets under review:
>  - Field Museum of Na accessed via ural His on ory

[README.txt](https://github.com/ParasiteTracker/tpt-reporting/files/4555148/README.txt)

**Comment by jhpoelen** [comment]
Thanks for sharing. I suspect this is related to #17 ( Repeating header in datasets_under_review.tsv ) which has since been fixed. I am generating a report on a server in Germany right now, so I can confirm in a bit.

**Comment by jhpoelen** [comment]
This issue has since been resolved. From https://zenodo.org/record/3778773/files/README  :

>Datasets under review:
> - Field Museum of Natural History IPT accessed via https://github.com/globalbioticinteractions/fmnh/archive/83cf7fca9608859f5d9f8bf702e2ab4c5e08af80.zip on 2020-04-29T22:33:45.300Z
