### ISSUE TITLE
Add elton.jar to version release

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#19]
@jhpoelen Presently not included in the dataset report version release.

**Comment by jhpoelen** [comment]
Thanks for sharing!

fixed via https://github.com/ParasiteTracker/tpt-reporting/commit/e4e617ae191eb5a357c189ac9b9c7897a21d35cc and https://github.com/ParasiteTracker/tpt-reporting/commit/41072ac2de4c9484864bcc5dfc509bccc9789d25 .
