### ISSUE TITLE
generate-report.sh not creating expected results on Mac

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#6]
@jhpoelen I am still getting unexpected results with the report script on Mac. I did update.

<img width="834" alt="Screen Shot 2020-02-05 at 1 50 54 PM" src="https://user-images.githubusercontent.com/1044474/73887370-3e52f980-4820-11ea-941f-dbd947a1bd4a.png">

**Comment by jhpoelen** [comment]
Thanks for sharing. Which version of elton are you using? ```elton version``` . If not 0.7.6 or higher, then please new version install via https://github.com/globalbioticinteractions/elton/#install . 

Then, re-run the report using:
```./generate-report.sh | tee report.log```

and attach report.log to this issue. Thanks for being patient.

**Comment by jhpoelen** [comment]
Just noticed a bug in the report archive constructions (see https://github.com/ParasiteTracker/tpt-reporting/commit/7a65ed953c126478dd37f14603953758ab26df1b) , am rebuilding using travis.

**Comment by jhpoelen** [comment]
I checked the report zip in tpt-reporting and it contained the expected content. Please verify/ confirm.

**Comment by seltmann** [comment]
@jhpoelen using version fa95b07

indexed_interactions_by_collection.tsv is not reporting any data
review_summary.tsv and review_summary_by_collection.tsv not reporting any data
indexed_interactions_simple.tsv and review_comments.tsv both null

<img width="977" alt="Screen Shot 2020-02-08 at 5 32 02 PM" src="https://user-images.githubusercontent.com/1044474/74094608-f25eb980-4a98-11ea-967a-8150b97d16ab.png">

Log contents:
using elton version 0.5.15
checking github api limits.checking github api limits......................................................................................................................................................................................................checking github api limits......checking github api limits.checking github api limits.checking github api limits.


---- distinct review comments by type ----
distinctReviewCommentCount	type	comment

---- indexed interaction record count by institutionCode, collectionId, collectionCode, and interaction type ----
institutionCode	collectionId	collectionCode	sourceCitation	indexedInteractionRecordCount	interactionTypeName	interactionTypeId

---- distinct review comment count by institution, collection and review comment type ----
institutionCode	collectionId	collectionCode	sourceCitation	distinctReviewCommentCount	type	comment

For more information, see /Users/katjaseltmann/Documents/elton/TPT-report/tpt-reporting//Users/katjaseltmann/Documents/elton/TPT-report/tpt-reporting/output/2020-02-08

Cannot create report because no interaction records were found. Please check log.

**Comment by jhpoelen** [comment]
Thanks for sharing the details on your report run!

Looks like you are using an older elton version (v0.5.15).  I've made some improvement to elton and the report generation script since, so please install v0.8.4 (https://github.com/globalbioticinteractions/elton#install) and get latest version of tpt-reporting repo and try again. 

Thanks for being patient as we are figuring out how to make this easier to use.

**Comment by seltmann** [comment]
@jhpoelen 
Updated and ran the reports. Log:
<img width="1001" alt="Screen Shot 2020-02-12 at 3 20 46 PM" src="https://user-images.githubusercontent.com/1044474/74386612-46281600-4dab-11ea-945e-e91c507d2414.png">

review_summary_by_collection.tsv and review_summary.tsv are still blank.

**Comment by jhpoelen** [comment]
Weird. Must be a mac thing. Let me use travis to test on mac also. Thanks for being patient.

**Comment by jhpoelen** [comment]
@seltmann looks like the travis Mac builder is happy now (see https://travis-ci.org/ParasiteTracker/tpt-reporting/jobs/649754690). Please update your script and confirm that it now runs on your mac.

In case you were wondering: the root cause was the tool ```zcat``` - fix was to do ```cat bla.txt | gunzip``` instead of just ```zcat bla.txt```

**Comment by seltmann** [comment]
@jhpoelen with the new update the review_summary_by_collection.tsv and review_summary.tsv are working. Closing issue.
