### ISSUE TITLE
Collection identifiers

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#7]
! expected the GUID e7c51ab1-870b-4ee8-9d62-092875ffa870 for your
UCSB-ICZ collection to be the same as the GBIF
http://www.gbif.org/dataset/d6097f75-f99e-4c2a-b8a5-b0fc213ecbd0 dataset
id. From @jhpoelen

**Comment by seltmann** [comment]
GBIF assigns a collection identifier when you publish a new collection. Symbiota also assigns a collection identifier. Many collections are published with iDigBio that are not published on GBIF.

**Comment by jhpoelen** [comment]
Good to know! 

Is there a mapping between Symbiota, GBIF and iDigBio collection ids?

**Comment by seltmann** [comment]
No, there is no mapping that I know of between those ids.

**Comment by neilcobb** [comment]
iDigBio only publishes specimen datasets so VectorBase is not on iDigBio but it is on GBIF
