### ISSUE TITLE
Report integration with GDocs

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#8]
@jhpoelen idea to put summary reports on GDoc and link to https://github.com/ParasiteTracker 

<img width="731" alt="Screen Shot 2020-02-12 at 2 40 54 PM" src="https://user-images.githubusercontent.com/1044474/74384440-17f40780-4da6-11ea-8300-9fdd4fffa31d.png">

<img width="721" alt="Screen Shot 2020-02-12 at 2 40 18 PM" src="https://user-images.githubusercontent.com/1044474/74384447-19bdcb00-4da6-11ea-927c-93174fe7ff15.png">

**Comment by seltmann** [comment]
@jhpoelen review summary no longer including "likely describes a biotic interaction." Can you please put that back into the summary for both overall and collection based?

"likely describes a biotic interaction" indicates the number of records that may be indexed by GloBI. 

An added addition would be "number of records examined for biotic interactions."

**Comment by jhpoelen** [comment]
I've added the "info" review types. 

Now, ```review_summary.tsv``` reads: 

distinctReviewCommentCount | type | comment
-- | -- | --
1454 | info | biotic interaction found
1 | issue | found unsupported interaction type with name: [In]
385 | issue | target taxon name missing
386 | info | no biotic interaction found

and ```review_summary_by_collection.tsv```


institutionCode | collectionId | collectionCode | sourceCitation | distinctReviewCommentCount | type | comment
-- | -- | -- | -- | -- | -- | --
UCSB | 6d00282e-3374-4a82-91a3-723372c9247b | UCSB | University of California Santa Barbara Algae Collection | 10 | info | biotic interaction found
UCSB | 6d00282e-3374-4a82-91a3-723372c9247b |   | University of California Santa Barbara Algae Collection | 133 | info | biotic interaction found
UCSB | e7c51ab1-870b-4ee8-9d62-092875ffa870 | IZC | University of California Santa Barbara Invertebrate Zoology Collection | 1311 | info | biotic interaction found
UCSB | e7c51ab1-870b-4ee8-9d62-092875ffa870 | IZC | University of California Santa Barbara Invertebrate Zoology Collection | 1 | issue | found unsupported interaction type with name: [In]
UCSB | e7c51ab1-870b-4ee8-9d62-092875ffa870 | IZC | University of California Santa Barbara Invertebrate Zoology Collection | 385 | issue | target taxon name missing
UCSB | e7c51ab1-870b-4ee8-9d62-092875ffa870 | IZC | University of California Santa Barbara Invertebrate Zoology Collection | 386 | info | no biotic interaction found

The total amount of examined records can be inferred by adding "biotic interaction found" and "no bioticinteraction found" categories.

**Comment by jhpoelen** [comment]
Correction - number of examined records is available after implementation of https://github.com/globalbioticinteractions/elton/issues/28 .

**Comment by jhpoelen** [comment]
@seltmann we ended up using Zenodo and review/indexed-interactions via https://depot.globalbioticinteractions.org/review/... . Suggest to close this issue.
